dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "3.7"

services:
  - docker

matrix:
  include:
    - python: "3.7"
      env: PLONE_VERSION=52
  sudo: true
  fast_finish: true

before_install:
  - docker pull plone:4.3
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt
  - cp test_plone$PLONE_VERSION.cfg buildout.cfg

install:
  - docker run -d -p 127.0.0.1:8085:8080 -e SITE="Plone" -e PLONE_ADDONS="redturtle.exporter.base" -e VERSIONS="redturtle.exporter.base=1.0.2" plone:4.3
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True annotate
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True
  - sleep 90
  - docker ps -a
  - sleep 60
  - docker ps -a

script:
  # Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test

after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - bin/pip install -q coveralls
  - bin/coveralls
